// generator.mjs — the GENERATOR LAYER wired into merkle-dag's dispatch.
//
// runBuild calls dispatch(injected) per ready node, where injected is ONLY the
// node spec { id, requirements, files, test, effective_hash } (Rule 1). A
// generator dispatch turns that spec into real files on disk and returns the
// signer; runBuild then runs the node's `test` (verifyNode) and only settles a
// signed ledger entry if the test passes. The seat never declares "done" — the
// test does.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { resolveUnder } from "../merkle-dag/vendor.mjs";
import { renderArchitectureMarkdown, stackLibraries } from "./research.mjs";

async function writeUnder(baseDir, rel, content) {
  const abs = resolveUnder(baseDir, rel);
  if (abs === null) throw new Error(`refusing to write outside project root: ${rel}`);
  await mkdir(path.dirname(abs), { recursive: true });
  await writeFile(abs, content);
}

// Wrap a `generateFiles(injected) -> { rel: content }` producer as a dispatch.
// Live: generateFiles calls a model seat through ai-peer-mcp. Tests: a
// deterministic producer (makeDemoGenerators) so the loop runs keyless.
export function generatorDispatch({ baseDir, generateFiles, signerForTask }) {
  return async (injected) => {
    let files;
    try {
      files = await generateFiles(injected);
    } catch (e) {
      return { ok: false, reason: `${injected.id}: generator threw: ${e?.message || String(e)}` };
    }
    if (!files || typeof files !== "object") {
      return { ok: false, reason: `${injected.id}: generator produced no files` };
    }
    for (const rel of injected.files) {
      if (!(rel in files)) return { ok: false, reason: `${injected.id}: missing required file ${rel}` };
      await writeUnder(baseDir, rel, files[rel]);
    }
    return { ok: true, signer: signerForTask(injected.id) };
  };
}

// 1x1 PNG (non-empty) standing in for a rendered verification screenshot.
const PNG_1x1 = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
  "base64"
);

const BRAND_CYAN = "#69e7ff";

function renderIndexHtml(arch) {
  const libs = stackLibraries(arch).join(", ");
  // First-screen "proof band": the markers check-frontend asserts.
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Convergence — deterministic communication forensics</title>
  <link rel="stylesheet" href="site/style.css" />
</head>
<body>
  <header class="proof-band">
    <h1>Convergence</h1>
    <p>Deterministic findings. Model chat explains them; it never authors the verdict.</p>
    <ul>
      <li><strong>Contract:</strong> deterministic discriminator over fixed inputs</li>
      <li><strong>Delivery:</strong> static-first SPA on a CDN (${libs})</li>
      <li><strong>Test posture:</strong> accuracy measured against a labeled set</li>
      <li><strong>TELOS gate:</strong> merge-readiness certified from disk + signatures</li>
    </ul>
  </header>
  <main id="app"></main>
</body>
</html>
`;
}

function renderStyleCss() {
  return `:root {
  /* Convergence brand cyan — asserted by the breakout file_contains check */
  --accent-cyan: ${BRAND_CYAN};
}
body { background: #0b0f14; color: #e6edf3; font-family: system-ui, sans-serif; margin: 0; }
.proof-band { padding: 3rem 2rem; border-bottom: 2px solid var(--accent-cyan); }
.proof-band h1 { color: var(--accent-cyan); margin: 0 0 .5rem; }
.proof-band ul { line-height: 1.7; }
`;
}

function renderVerificationMd(arch) {
  return `# Verification

Generated by the TELOS SaaS forge and re-verified by the gate against disk.

- \`web/site/style.css\` carries the brand token \`${BRAND_CYAN}\`.
- \`web/index.html\` exposes the first-screen proof band (contract, delivery, test posture, TELOS gate).
- \`docs/verification/s03-dynamics-discriminator.png\`, \`s04-scorecard.png\` — rendered evidence.

Stack: ${stackLibraries(arch).join(", ")}.
`;
}

// Deterministic, keyless generators keyed by task id. This is the stand-in for
// live model-seat generation: same dispatch contract, no API keys, so the whole
// research -> generate -> verify -> gate loop runs in tests and CI.
export function makeDemoGenerators(arch) {
  return async (injected) => {
    switch (injected.id) {
      case "architecture":
        return { "docs/ARCHITECTURE.md": renderArchitectureMarkdown(arch) };
      case "frontend-brand-experience":
        return {
          "web/site/style.css": renderStyleCss(),
          "web/index.html": renderIndexHtml(arch),
          "web/VERIFICATION.md": renderVerificationMd(arch),
          "docs/verification/s03-dynamics-discriminator.png": PNG_1x1,
          "docs/verification/s04-scorecard.png": PNG_1x1
        };
      default:
        throw new Error(`no generator for task '${injected.id}'`);
    }
  };
}
