import assert from "node:assert/strict";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { browser } from "./browser.mjs";
import { serve } from "./server.mjs";
import { button, station, GRAPH_PROBE, ready, pause } from "./scenarios.mjs";
import { COMMANDS } from "../state.js";
import { browserHarnessHash, buildIdentity } from "../../scripts/verification-identity.mjs";
const root = path.resolve(process.argv[2] ?? new URL("../../dist/", import.meta.url).pathname), output = process.argv[3];
const sha = bytes => createHash("sha256").update(bytes).digest("hex");
const buildBytes = await readFile(path.join(root, "build-manifest.json"));
const buildManifest = JSON.parse(buildBytes);
assert.equal(buildManifest.kind, "native-static-build");
for (const [file, hash] of Object.entries(buildManifest.files)) {
    assert.equal(sha(await readFile(path.join(root, file))), hash, `Built bytes drifted: ${file}`);
}
const server = await serve(root, { publicRoot: path.resolve(root, "../public") }), b = await browser(process.env.BROWSER_PATH);
const completed = [], seen = new Set(), errors = [];
const off = b.onEvent(m => { if (m.method === "Runtime.exceptionThrown")
    errors.push(m.params.exceptionDetails); });
try {
    const p = await b.page();
    await p.command("Page.addScriptToEvaluateOnNewDocument", { source: GRAPH_PROBE });
    await p.goto(server.url + "/?e2e=1");
    await ready(p);
    const text = selector => p.evaluate(`document.querySelector(${JSON.stringify(selector)})?.textContent`);
    const progress = () => text('[data-testid="progress"]');
    const click = async (command) => { await p.click(button(command)); seen.add(command); };
    await click("NEXT_STATION");
    assert.equal(await progress(), "02 / 06");
    await click("PREV_STATION");
    assert.equal(await progress(), "01 / 06");
    await p.click(station(2));
    seen.add("GO_STATION");
    assert.equal(await progress(), "03 / 06");
    completed.push("next/previous/direct station controls");
    await click("PULL_THREAD");
    assert.equal(await text(button("RELEASE_THREAD")), "Release thread");
    await click("RELEASE_THREAD");
    assert.equal(await text(button("PULL_THREAD")), "Pull thread");
    await click("OPEN_EVIDENCE");
    assert.match(await text('[data-testid="evidence-panel"]'), /EVIDENCE/);
    await click("CLOSE_EVIDENCE");
    assert.equal(await text('[data-testid="evidence-panel"]'), undefined);
    completed.push("tension and evidence toggles");
    await click("TOGGLE_THEME");
    assert.equal(await p.evaluate("document.documentElement.dataset.theme"), "light");
    await click("TOGGLE_MOTION");
    assert.equal(await p.evaluate("document.documentElement.dataset.motion"), "reduced");
    completed.push("theme and reduced motion");
    await p.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(button("SCRUB_TIME"))});e.value='3';e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    seen.add("SCRUB_TIME");
    assert.equal(await progress(), "04 / 06");
    await click("EXPORT");
    assert.equal(await text(button("EXPORT")), "Export (1)");
    await click("RESET");
    assert.equal(await progress(), "01 / 06");
    completed.push("timeline/export counter/reset");
    await click("ENTER_GRAPH");
    await ready(p);
    assert.match(await text('[data-testid="compound-citation"]'), /Lachesis.*Atropos/);
    await click("SELECT_NODE");
    assert.match(await text('[data-testid="node-detail"]'), /blast radius.*Lachesis.*Atropos/);
    await click("CLEAR_NODE");
    assert.equal(await text('[data-testid="node-detail"]'), undefined);
    await click("EXIT_GRAPH");
    assert.equal(await progress(), "01 / 06");
    completed.push("graph/citation/selection/return");
    assert.deepEqual([...seen].sort(), [...COMMANDS].sort());
    await p.evaluate(`document.querySelector(${JSON.stringify(button("EXPORT"))}).focus()`);
    assert.equal(await p.evaluate("document.activeElement.dataset.testid"), "cmd-EXPORT");
    await p.command("Input.dispatchKeyEvent", { type: "keyDown", key: "Enter", code: "Enter", text: "\r", unmodifiedText: "\r", windowsVirtualKeyCode: 13 });
    await p.command("Input.dispatchKeyEvent", { type: "keyUp", key: "Enter", code: "Enter", windowsVirtualKeyCode: 13 });
    assert.equal(await text(button("EXPORT")), "Export (1)");
    assert.equal(await p.evaluate("document.activeElement.dataset.testid"), "cmd-EXPORT");
    completed.push("keyboard activation retains focus");
    await p.evaluate("window.__lose=document.querySelector('canvas').getContext('webgl2').getExtension('WEBGL_lose_context');window.__lose.loseContext()");
    await p.wait("document.documentElement.dataset.graphics === 'context-lost'");
    await click("NEXT_STATION");
    assert.equal(await progress(), "02 / 06");
    await pause(200);
    await p.evaluate("window.__lose.restoreContext()");
    await p.wait("document.documentElement.dataset.graphics === 'ready'");
    completed.push("context loss keeps controls and restores graphics");
    await p.command("Emulation.setDeviceMetricsOverride", { width: 900, height: 600, deviceScaleFactor: 2, mobile: false });
    await p.wait("document.querySelector('canvas').width===1800 && document.querySelector('canvas').height===1200");
    completed.push("resize and DPR update drawing buffer");
    await p.close();
    const fallback = await b.page();
    await fallback.command("Page.addScriptToEvaluateOnNewDocument", { source: "const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){return type.startsWith('webgl')?null:original.call(this,type,...rest)};" });
    await fallback.goto(server.url + "/?e2e=1");
    await fallback.wait("document.documentElement.dataset.graphics === 'unavailable'");
    await fallback.click(button("ENTER_GRAPH"));
    assert.match(await fallback.evaluate("document.querySelector('[data-testid=compound-citation]').textContent"), /Lachesis/);
    completed.push("WebGL unavailable retains entire interaction layer");
    await fallback.close();
    const deep = await b.page();
    await deep.command("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] });
    await deep.goto(server.url + "/?view=graph");
    await deep.wait("document.querySelector('[data-testid=compound-citation]')");
    assert.equal(await deep.evaluate("document.documentElement.dataset.motion"), "reduced");
    completed.push("deep link and OS motion preference");
    await deep.close();
    assert.deepEqual(errors, []);
    const receipt = { status: "pass", commands_executed: [...seen], completed, browser: await b.send("Browser.getVersion"), build_manifest_sha256: await buildIdentity(root), harness_sha256: await browserHarnessHash() };
    if (output) {
        await mkdir(path.dirname(output), { recursive: true });
        await writeFile(output, JSON.stringify(receipt, null, 2) + "\n");
    }
    console.log(JSON.stringify(receipt, null, 2));
}
finally {
    off();
    await b.close();
    await server.close();
}
